/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BingoCardInfo: typeof import('./src/components/BingoCardInfo.vue')['default']
    BingoCardSelector: typeof import('./src/components/BingoCardSelector.vue')['default']
    BingoGrid: typeof import('./src/components/BingoGrid.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
